### ISSUE TITLE
exception when no web translate result

### ISSUE THREAD

**Issue by nodejh** [nodejh/node-cli-translate#1]
There is an exception when no web translate result.

当没有网络释义结果的时候，程序发生错误，没有捕获异常。

➜  t snippest
  [BASIC]
  vt. 剪去：；用…剪(或剪的动作)：   vi. 剪：；发出剪刀的咔嚓声：   n. 剪；剪刀的咔嚓咔嚓声；剪的痕迹

  [WEB]
/Users/jh/.nvm/versions/node/v7.3.0/lib/node_modules/node-cli-translate/translate.js:43
      web.map((item) => {
         ^

TypeError: Cannot read property 'map' of undefined
    at IncomingMessage.<anonymous> (/Users/jh/.nvm/versions/node/v7.3.0/lib/node_modules/node-cli-translate/translate.js:43:10)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by nodejh** [comment]
fixed: 通过监听 `uncaughtException` 事件来捕获网络错误。
