### ISSUE TITLE
无法取得翻译结果时产生异常 ReferenceError: parsed is not defined

### ISSUE THREAD

**Issue by nodejh** [nodejh/node-cli-translate#2]
➜  t he
/Users/jh/.nvm/versions/node/v7.6.0/lib/node_modules/node-cli-translate/translate.js:30
        return console.log(colors.Reset, colors.fg.Red, parsed, colors.Reset);
                                                        ^

ReferenceError: parsed is not defined
    at IncomingMessage.<anonymous> (/Users/jh/.nvm/versions/node/v7.6.0/lib/node_modules/node-cli-translate/translate.js:30:57)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by nodejh** [comment]
Fixed.  Use 'uncaughtException' catches the exception.

https://github.com/nodejh/node-cli-translate/commit/d91a27e45bd3d03c19e7aeed6bfc367ff1ada5b1
