### ISSUE TITLE
 Unhandled 'error' event Error: getaddrinfo ENOTFOUND 

### ISSUE THREAD

**Issue by nodejh** [nodejh/node-cli-translate#3]
events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND fanyi.youdao.com fanyi.youdao.com:80
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

**Comment by nodejh** [comment]
fixed https://github.com/nodejh/node-cli-translate/commit/d91a27e45bd3d03c19e7aeed6bfc367ff1ada5b1
